spring.application.name=Smileapp
#Configuracion de la ruta base para la API v1
server.servlet.context-path=/api/v1
spring.datasource.url=jdbc:postgresql://ep-autumn-darkness-a5xg6esj.us-east-2.aws.neon.tech:5432/smileApp
spring.datasource.username=smileApp_owner
spring.datasource.password=ZyojD7evBUY4
#spring.datasource.url=jdbc:postgresql://localhost:5432/smile
#spring.datasource.username=postgres
#spring.datasource.password=adminadmin
spring.jackson.time-zone=America/Lima
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Jwt configuracion
#longitud 112
jwt.secret=1pOa45r7K6d9LmNqXiTgU1sVzY2wCjBy4fhEeZ9rCj8mL0kBtNhP3Q7xRaMfVnYp6GdTxSq9R1pOa45r7K6d9LmNqXiTgU1sVzY2wCjBy4fhEeZ9rCj8mL0kBtNhP3Q7xRaMfVnYp6GdTxSq9R
jwt.validity-in-seconds=2592000

#Configuracion para Subir Imagenes a la base(el archivo creado "uploads" tiene que tener permiso de escritura)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB